name: CI
on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      TEST_OUTPUT: ${{ github.workspace }}/test_output.txt
      COVERAGE_FILE: ${{ github.workspace }}/coverage.txt
      COVERAGE_ALL: ${{ github.workspace }}/coverages.out
      HAS_GO_FILES: "false"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pcregrep
        run: |
          sudo apt-get update
          sudo apt-get install -y pcregrep

      - name: Get changed folders
        id: changed
        run: |
          changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.go$')
          echo "changed=$changed"
          # Создаем пустой массив для хранения папок с функциями
          folders_with_functions=()
          
      - name: Print changed folders
        run: |
          echo "CHANGED FOLDERS:  ${{ steps.changed.outputs.folders }}"
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Install linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --config ${{ github.workspace }}/.golangci.yml ${{ steps.changed.outputs.folders }}
